version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API Port
      - "9001:9001"   # Console Port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - minio
  ingestor:
    image: dakshsawhneyy/sentiment-analysis-ingestor:latest
    container_name: ingestor
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on: [ minio ]
    volumes:
      - ./data/raw:/app/data/raw
    networks:
      - minio
  processor:
    image: dakshsawhneyy/sentiment-analysis-processor:latest
    container_name: processor
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on: [ minio, ingestor ]
    networks:
      - minio
  trainer:
    image: dakshsawhneyy/sentiment-analysis-trainer:latest
    container_name: trainer
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}
    depends_on: [ minio , ingestor, processor]
    networks:
      - minio
  validator:
    image: dakshsawhneyy/sentiment-analysis-validator:latest
    container_name: validator
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}
    depends_on: [ minio, ingestor, processor, trainer ]
    networks:
      - minio
  server:
    image: dakshsawhneyy/sentiment-analysis-server:latest
    container_name: server
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
    - ./data/processed:/app/data/processed
    depends_on: [ minio ]
    networks:
      - minio
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prom.yml:/etc/prometheus/prometheus.yml
    networks:
      - minio
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - minio

volumes:
  minio_data:
networks:
  minio: