name: CI - Build & Test

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  devsecops-security-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   with:
      #     projectBaseDir: .
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_PROJECT_KEY: daksh_sam_ops_pipeline
      #     SONAR_ORGANIZATION: daksh
      - name: Run Bandit security scan
        run: |
          pip install bandit
          bandit -r src --severity-level high

  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Build & push ingestor
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-ingestor:${{ steps.vars.outputs.TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-ingestor:latest -f src/ingestor/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-ingestor:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-ingestor:latest
      - name: Build & push processor
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-processor:${{ steps.vars.outputs.TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-processor:latest -f src/processor/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-processor:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-processor:latest
      - name: Build & push trainer
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-trainer:${{ steps.vars.outputs.TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-trainer:latest -f src/trainer/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-trainer:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-trainer:latest
      - name: Build & push validator
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-validator:${{ steps.vars.outputs.TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-validator:latest -f src/validator/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-validator:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-validator:latest
      - name: Build & push Server
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-server:${{ steps.vars.outputs.TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-server:latest -f serving/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-server:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-analysis-server:latest
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        working-directory: infrastructure/main_infra
        run: terraform init
      # - name: Terraform Plan
      #   working-directory: infrastructure/main_infra
      #   run: terraform plan -out=tfplan
      - name: Terraform Apply
        working-directory: infrastructure/main_infra
        run: terraform apply -auto-approve -lock=false
        env:
          minio_user: ${{ secrets.minio_user }}
          minio_password: ${{ secrets.minio_password }}
          mlflow_uri: ${{ secrets.mlflow_uri }}
          mlflow_user: ${{ secrets.mlflow_user }}
          mlflow_pass: ${{ secrets.mlflow_pass }}